### ISSUE TITLE
elastic4s-streams and elastic4s-http-streams together

### ISSUE THREAD

**Issue by To-om** [sksamuel/elastic4s#1122]
I'd like to use HTTPClient or TCPClient depending on application configuration. So I include "elastic4s-http" and "elastic4s-tcp" in the dependencies. I find it unfortunate that both client doesn't share a same super class, but it is not be big deal.

My problem is that I want to use scroll search. It seems that "elastic4s-streams" and "elastic4s-http-streams" can't work together as they provide classes with identical name, in the same package name. Both have `com.sksamuel.elastic4s.streams.ReactiveElastic` and `com.sksamuel.elastic4s.streams.ReactiveElasticScrollPublisher`.

Am I missing something ? How can I include both tcp streams and http streams ?

**Comment by sksamuel** [comment]
If you really want to use both, you just need to reference by full class name right. `com.sksamuel.elastic4s.streams.ReactiveElastic` rather than `import com.sksamuel.elastic4s.streams.ReactiveElastic; ReactiveElastic`. Just like you do if you want to use java.util.List and scala.collection.List in the same file.

However be aware, the TCP client is now deprecated and elasticsearch are going to remove it in version 7.

**Comment by To-om** [comment]
I may have misheard. The class `com.sksamuel.elastic4s.streams.ReactiveElastic` is present in "elastic4s-streams" and in "elastic4s-http-streams". In the classpath, one overrides the other.

I saw that TCP client is deprecated. I would have preferred support both for better transition but it is harder task than I expected. The results of operation on TCPClient and HTTPClient are not consistent (`SearchResponse` Vs `RichSearchResponse`).

**Comment by sksamuel** [comment]
Oh yes I see, if the FQN is the same then you can't do what you want. 

I could add an alias into the TCP or HTTP Steams so you have another FQN to reference it by?
