### ISSUE TITLE
Executable Typeclass Redux

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#1279]
This is a single issue to cover the following issues:

- #1180 #1185 The current implementation of "Show" only shows the body, it should also show headers, method and url
- #1206 Allow parameterization over the effect type (Future, Monix Task etc)
- #1278 Using an ADT _and_ an Either is silly
- Removing the TCP client from 7.0

**Comment by ches** [comment]
I think you mentioned a prerelease on #1206 (non-SNAPSHOT I presume)—is that coming sometime soon? It would be nice if the extra API noise resolved from #1278 was short-lived in the wild, and recent removal of `TcpClient` from testkit is appealing too, it helps relieve dependency pains in projects that use the HTTP client for production code so otherwise aren't so coupled to Elasticsearch version lockstep.

**Comment by ches** [comment]
The brief excursion into the `Either` was a major API difference… it's painful for someone to program against that API because they're on a 6.2.x Elasticsearch and it's what they find as current for that version, and then need to change it all again next time they update. Even worse if you migrate from an earlier elastic4s to 6.2 and so you made all these breaking changes once already.

Would it be a tremendous pain to backport this to 6.2.x? We're on that minor version of Elasticsearch at work and it's probably unlikely to change for awhile. Changelogs haven't been updated since 6.1 so I'll have to poke around some branch comparison to get idea of what else changed and how much time I'd need to invest to attempt it.

We might be okay to run 6.3 HTTP client against a 6.2 Elasticsearch, but it sounds like asking for trouble or at least confusion in a team.
