### ISSUE TITLE
Not found: value HttpClient

### ISSUE THREAD

**Issue by jgnieuwhof** [sksamuel/elastic4s#1455]
I'm fairly new to Scala, so please forgive me if this should be obvious.

I've tried running the example here: https://github.com/sksamuel/elastic4s/blob/master/samples/elastic4s-http-client-sbt/src/main/scala/com/sksamuel/elastic4s/samples/HttpClientExampleApp.scala, and despite my best efforts continually receive the following compile error:
```
[error] /home/jgnieuwhof/projects/scala-test/src/main/scala/jgnieuwhof/Main.scala:13:16: not found: value HttpClient
[error]   val client = HttpClient(ElasticsearchClientUri("localhost", 9200))
[error]                ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

I've added the following to my `build.sbt` file:
```
    libraryDependencies ++= Vector(
      ...,
      "com.sksamuel.elastic4s"      %%  "elastic4s-core"  % "6.3.1",
      "com.sksamuel.elastic4s"      %%  "elastic4s-http"  % "6.3.1"
    )
```

Any ideas? Thanks in advance for any help.

**Comment by ches** [comment]
There have been a lot of changes recently and the documentation is lagging behind, and apparently samples are broken too… Your best bet is to use tests in the elastic4s-tests subproject as a reference, for instance:

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/aggs/TermsAggregationHttpTest.scala

You can see [the DockerTests suite mixin][1] for how an HTTP client instance is initialized:

```scala
import com.sksamuel.elastic4s.http.{ElasticClient, ElasticProperties}

val client = ElasticClient(ElasticProperties("http://localhost:9200"))
```

The doc site at https://sksamuel.github.io/elastic4s/docs/ is even more outdated than samples or README I believe, so don't even bother looking there… stick to the tests. I'm going to try to help out with sending some doc update PRs, because I'm going through similar pain of working through misinformation.

[1]: https://github.com/sksamuel/elastic4s/blob/022b56d01d37945ff6b697b33ec1567732aae33b/elastic4s-testkit/src/main/scala/com/sksamuel/elastic4s/testkit/DockerTests.scala

**Comment by jgnieuwhof** [comment]
@ches thanks for the quick response! I understand the woes of maintaining docs, no worries there. a brief disclaimer near the top of the readme to point people at the tests may help in the meantime; mind you I probably should have had the sense to look at the tests in the first place.

 🤷‍♂️ live & learn 🤷‍♀️

**Comment by ches** [comment]
[I'm just another user, not a maintainer 😄]

Got some doc updates kicked off in #1456, pitch in if you're learning the library and find things out of date!

**Comment by vreyespue** [comment]
Here an update related to `elastic4s` version 7.3.1 on scala 2.12.10

In my setup I also got errors (not found) when trying to use `HttpClient` (`elastic4s-core`,`elastic4s-http-streams` and `elastic4s-client-esjava` version 7.3.1).

The solution: you should be able to find and use `JavaClient`, an [implementation][1] of HttpClient that wraps the Elasticsearch Java Rest Client.

An example of how to use the `JavaClient` can be found [here][1].

Thus, your code should look like the following:

    import com.sksamuel.elastic4s.http.JavaClient
    import com.sksamuel.elastic4s.{ElasticClient, ElasticDsl, ElasticProperties}
    ...
    val client = ElasticClient(JavaClient(ElasticProperties(uri)))


  [1]: https://github.com/sksamuel/elastic4s/blob/master/elastic4s-testkit/src/main/scala/com/sksamuel/elastic4s/testkit/DockerTests.scala
