### ISSUE TITLE
Update examples and documentation for 7.x

### ISSUE THREAD

**Issue by balexander** [sksamuel/elastic4s#1936]
Is there a plan to update the examples in the documentation, or the documentation as a whole, to represent the changes that come along with version 7.x? This small [migration guide](https://github.com/sksamuel/elastic4s/issues/1723) was helpful but the samples in the documentation and the examples in the readme with the TCP client were not.

**Comment by rcarranza-carecloud** [comment]
A proper well written and updated **Changelog** would be extremely useful. I'm trying to migrate from 6.0.4 to 7.3.1 and I have to read Issues to find out the changes that were made.

**Comment by tjarvstrand** [comment]
:+1: This would be extremely useful. I just came here and the current README is just plain misleading. I don't even know where to start

**Comment by arsidnal16** [comment]
I am trying to migrate from ES 7 and hence had to upgrade to elastic4s-v7.x and its very confusing because even with https://github.com/sksamuel/elastic4s/issues/1723, the function defintion in ElasticClient and HTTP client is different. A well written readme will be very useful and also will help people use this with changes in code.

**Comment by sksamuel** [comment]
The docs have been overhauled to be current. You should find them a hell of alot more useful now !
