### ISSUE TITLE
Put type mapping

### ISSUE THREAD

**Issue by ornicar** [sksamuel/elastic4s#24]
Add a way to set a type mapping without creating an index. http://www.elasticsearch.org/guide/reference/api/admin-indices-put-mapping/

**Comment by RPGambit2** [comment]
Stephen, is there a way to use putMapping when your index is already created. For example, I use update to create my index and I add fields as I need to the elastic search document using update and docAsUpsert. I would like to add one of my fields which is a Long (scala) into elasticsearch as a date since it is in milliseconds since the epoch. I found putMapping, but I can't figure out how to use it with an already created index.

I'm thinking something like this:

        elasticSearchClient.execute {putMapping("elk-indexing-node/elk-indexing-group") mapping (
          "CreatedBy" typed DateType)
        }

**Comment by sksamuel** [comment]
Yes you can update an existing mapping to add new fields.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html

**Comment by RPGambit2** [comment]
Are there any examples of this using elastic4s?  I cannot seem to figure out the syntax.   I would like to do the update and the mapping of the field in the same command.  Not sure if that is possible:

**Comment by sksamuel** [comment]
When you create the index you can set custom dates which you could use for this.

**Comment by RPGambit2** [comment]
Sk, I am creating the index by doing the update.    It gets automatically created when I do the

elasticSearchClient.execute {
      update ((elkEnrichmentStatsJobDTOMessage.JobId, elkEnrichmentStatsJobDTOMessage.RunId)) in "elk-indexing-node/elk-indexing-group" docAsUpsert (
        "CreatedBy" -> elkEnrichmentStatsJobDTOMessage.CreatedBy......

**Comment by RPGambit2** [comment]
Stephen,

Sorry to bother you.   I cannot figure out how to get my times correct so
they work in Kibana via Elasticsearch.

I have them in milliseconds since the epoch and I do the following:

// Found this on the internet.  I believe you wrote it as an example for Date

case class CustomDateFieldValue(name: String, date: Date) extends FieldValue {
  private val dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")

  def output(source: XContentBuilder): Unit = {
    source.field(name, dateFormat.format(date))
  }
}


// Trial #1

// CreatedOnTimestamp is a Long that is milliseconds since the epoch

CreatedOnTimestamp =
elkEnrichmentStatsSubmitRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn

elkIndexingStatsElasticSetupMessage.client.execute {

  update((JobId, RunId)) in elasticNodeGroup4Stats docAsUpsert(
     "CreatedOnTimestamp" -> CreatedOnTimestamp,
  ) retryOnConflict (numberOfRetries)
}

// Trial #2

indexInto (elkIndexingStatsElasticSetupMessage.elasticIndex,
elkIndexingStatsElasticSetupMessage.elasticGroup) fieldValues (
CustomDateFieldValue("CreatedOnTimestamp", Date())
)


For my first Trial #1, I just get milliseconds in elasticsearch, but
no way to format it

For the second Trial #2, using your example, I can't get it to work.
It is looking for parameters for Date() and I tried

everything.   I'm not sure which library should be imported for this
particular "Date" function either.


Any help would be appreciated.   I just want to get a date from scala
into elasticsearch so that elastic search knows its

a date and not a Long.


Thanks!


Don

**Comment by sksamuel** [comment]
Are you setting the field type to date when you create the index.

**Comment by RPGambit2** [comment]
Stephen,

This is the exact code that creates the index.   I use update to create the
index.   The CreatedOnTimestamp field is a Long (milliseconds since the
epoch).   How do I change the field type date?  I tried different things
but nothing has worked.  I tried using Trial 2 but I get build errors and
I'm not sure how to fix it.

> // Trial #1
>
> // CreatedOnTimestamp is a Long that is milliseconds since the epoch
>
> CreatedOnTimestamp =
> elkEnrichmentStatsSubmitRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn
>
> elkIndexingStatsElasticSetupMessage.client.execute {
>
> update((JobId, RunId)) in elasticNodeGroup4Stats docAsUpsert(
> "CreatedOnTimestamp" -> CreatedOnTimestamp,
> ) retryOnConflict (numberOfRetries)
> }

**Comment by RPGambit2** [comment]
Stephen,

Is it possible to show me how it is done using your elastic4s API?  I'm
getting confused.

I need to take a Long in scala and get it into a date field in
Elasticsearch using your API.

Thanks!

Don
