### ISSUE TITLE
Possible to make elastic4s 7.x es 6.8.15 compatible?

### ISSUE THREAD

**Issue by Habitats** [sksamuel/elastic4s#2403]
We're in the middle of an upgrade process from 6.8.15 -> 7.x, but struggle a bit with making a smooth transition since there's so many changes in the 7.x version. I.e. upgrade the code before we upgrade the cluster (and get cross-compatibility while doing it).

For our [spark elastic library](https://github.com/elastic/elasticsearch-hadoop/), the latest 7.12.0 seems to be fully compatible with ES 6.8.15.

Is it possible to get elastic4s 7.x working with a 6.8.15 cluster, or are we attempting the impossible?

**Comment by sksamuel** [comment]
All elastic4s does is generate JSON and send it to the endpoints (basically).
Since the json structure doesn't change that much, I'd imagine 7.x will work for 95% of stuff on 6.8 out of the box (assuming something wasn't removed).
And if that doesn't work, you can just write your own typeclass for a particular handler (which generates the json) and you're good to go.
