### ISSUE TITLE
termsFilter with an array 

### ISSUE THREAD

**Issue by dpiscia** [sksamuel/elastic4s#274]
Hi,
How can I pass an array as argument for termsFilter function?
For Example, 
I have an array defined like Array_list= Array("one","two")
If I write termsFilter("field_name",Array_list(0),Array_list(1)) then it works but if I write termsFilter("field_name",Array_list) does not work.
many thanks in advanced

**Comment by JD557** [comment]
I think that if you cast it to a vararg (_*) it should work.

```
val arr = Array("one","two")
termsFilter("field_name", arr:_*)
```

I'm not sure if this can be solved by just adding a `def termsFilter(field: String, values: Iterable[Any]): TermsFilterDefinition`, though (since an `Iterable[Any]` is also an `Any`), but after some quick tests in the REPL this seems possible.

**Comment by dpiscia** [comment]
Many Thanks!! It works with the casting!
