### ISSUE TITLE
How do I delete an Index programmatically?

### ISSUE THREAD

**Issue by ikenna** [sksamuel/elastic4s#3]
Thanks for this library!

Please how do I delete an index programmatically? Can't seem find a the api for this.

**Comment by RPGambit2** [comment]
Anyone know if this is still available?  I can't find the API to delete a whole index.

**Comment by sksamuel** [comment]
```scala
client.exec {
  deleteIndex("myindex")
}
```

**Comment by RPGambit2** [comment]
Thanks Stephen.   I needed the import and that was the issue.  It deleteIndex wasn't coming up underlined in Intellij so I needed to try and figure it out.   I found it in your code and that fixed the issue.  

Thanks!

Don

**Comment by RPGambit2** [comment]
Stephen,

Just a quick question.

import com.sksamuel.elastic4s.ElasticDsl.deleteIndex

// Delete the old index that we no longer need since it passed its lifetime
val resp = client4Elastic.execute {
deleteIndex(Seq(elasticIndexToDelete))
}



Get build error:

Error:(281, 49) could not find implicit value for parameter
executable: com.sksamuel.elastic4s.Executable[com.sksamuel.elastic4s.indexes.DeleteIndexDefinition,R,Q]
              val resp = client4Elastic.execute {

Error:(281, 49) not enough arguments for method execute: (implicit
executable: com.sksamuel.elastic4s.Executable[com.sksamuel.elastic4s.indexes.DeleteIndexDefinition,R,Q])scala.concurrent.Future[Q].
Unspecified value parameter executable.
              val resp = client4Elastic.execute {


Any ideas?
