### ISSUE TITLE
Scalalogging dependency

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#323]
Recent versions of elastic4s depends on old version of scalalogging. This causes incompatibility problem with our code that uses scalalogging 3.1.0. 

I found that logging is actually used only in testkit, maybe you can remove this dependency from core artifact?

**Comment by sksamuel** [comment]
Core should only use test kit in test scope so that's a bug anyway.

**Comment by sksamuel** [comment]
So the reason I use the old version is because I need 2.10 compatibility. I think the new one (3.x) is only 2.11+.

It's really annoying its not cross built. I'll remove it for now, but I will need to add something in, because I want to add the "json" format logging to the client. Maybe I'll just use slf4j.
