### ISSUE TITLE
is ElasticClient thread safe? (connection pooling)

### ISSUE THREAD

**Issue by janghwan** [sksamuel/elastic4s#385]
Hi guys.
I wonder what's the best usage of `ElasticClient`
Is it okay -  in terms of performance - to call `ElasticClient.remote()` every time I need a client?
Or should I cache a singleton object and share among threads?

**Comment by andrestc** [comment]
We are currently using it as a singleton object. I think all that ElasticClient does is create an [org.elasticsearch.client.transport.TransportClient](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/client/transport/TransportClient.java). It seems that he keeps a pool of threads for sending the requests over the cluster; so i don't think its a good idea to call it every time when making a request.

**Comment by sksamuel** [comment]
@janghwan Definitely cache it. The reason is an Elasticsearch client is a clever beast. It pings the cluster to become cluster-aware so it can route queries to the right nodes. Each time you create one there's this small overhead. In addition to the internal thread pools it creates (about 30 threads).

**Comment by janghwan** [comment]
Thanks! @andrestc @sksamuel

**Comment by fpopic** [comment]
object Elastic4sUtils {

  val client = ElasticClient.transport("elasticsearch://localhost:9300")

  def getClient : ElasticClient = {
    client
  }
}

Is that good example of it or ?
