### ISSUE TITLE
Improve Bool block to avoid the "last return" issue

### ISSUE THREAD

**Issue by michael-read** [sksamuel/elastic4s#580]
Using ES v2.3.3 with elastic4s v2.3.0 on a local node. Client creation looks like this:
`val client = ElasticClient.remote("localhost", 9300)`

For example:
`search in "index"->"type" query { 
        bool {        
          must (
            existsQuery("location")
          )
          not (
            existsQuery("website")
          )           
        }      
      }`

returns the returns the result from the "not". If the "must" and "not" are reversed then the "must" results are returned.

The following **rawQuery** returns the proper result:
`search in "index"->"type" rawQuery {
        """
         {
            "bool": {
                "must": {
                    "exists": {
                        "field": "location"
                    }
                },            
                "must_not": {
                    "exists": {
                        "field": "website"
                    }
                }
            }
        }
`

**Comment by sksamuel** [comment]
The bool block is rubbish, it always leads to questions and errors. The issue you're having is that Scala returns the last value in a block, so

```bool {
     must(..),
     not(..)
}```

It's no different to

```val a = { 
 "sam"
"ham"
}
```
`a is now "ham" and "sam" is thrown away. So it's a scala-ism rather than an elastic4s issue as such, but I'm going to change `bool` to stop people falling into that trap.
