### ISSUE TITLE
5.0.0-RC1 combined with spark 2.0.0

### ISSUE THREAD

**Issue by TomLous** [sksamuel/elastic4s#663]
First of all: Thank you for all the effort you are putting in this project.
Second: I'm no sbt, elastic or scala expert (yet) so bare with me if I say something stupid.

Situation: I am getting issues building sbt projects with the 5.0.0-RC1 combined with spark 2.0.0

Apparently the elastic4s module forces 

> "io.netty" % "netty-common" % "4.5.1.Final",

 while spark uses 

> "io.netty" % "netty-all" % "4.0.29.Final"

Which still compiles but generates runtime errors whilst creating the spark context:

> An exception or error caused a run to abort: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor; 
> java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;

The elastic4s 2.3.1 worked fine and didn't seem to include netty-common, but I really want to use the 5.0.0 :-)

So now I'm using:

` libraryDependencies += ("com.sksamuel.elastic4s" %% "elastic4s-core" % "5.0.0-RC1").exclude("io.netty", "netty-common")`

which 'works' but I don't really feel comfortable about it.

**Comment by sksamuel** [comment]
Hi,

Had the same issue myself. It's Elasticsearch that's forcing 4.1.5 not elastic4s, so the same issue would persist with the java client etc.
https://repo1.maven.org/maven2/org/elasticsearch/plugin/transport-netty4-client/5.0.0/transport-netty4-client-5.0.0.pom

My solution was to upgrade spark to 4.0.26. If you are using spark on yarn just replace the jar in the spark folder.

Otherwise it might be possible to use netty3 only by creating your own TransportClient and wrapping ElasticClient in it. Take a look at PreBuiltTransportClient, and maybe clone it and remove netty4. If that works I could include it in elastic4s perhaps.

**Comment by TomLous** [comment]
Ok. Thanks! I'll give it a go.
