### ISSUE TITLE
Docs says val client = ElasticClient.transport("host1", 9300)

### ISSUE THREAD

**Issue by fancellu** [sksamuel/elastic4s#671]
Doesn't work for me using 5.0.0

Do I need some other import? Or is the docs out of sync?

Thanks.

**Comment by sksamuel** [comment]
The docs are out of date, you need to use `ElastiClient.transport(uri)`. The uri can be created from `ElasticsearchClientUri(host, port)`

**Comment by fancellu** [comment]
OK, thought as much. Thanks.

**Comment by sksamuel** [comment]
Docs updated.

**Comment by RPGambit2** [comment]
I'm having a similar issue.  I changed from my local PC Elasticsearch Server to a company provided server.   I am having issues and can't create a client.

This used to work prior to trying to use the company server:

// Create our client that will talk to Elasticsearch server to index Kafka data
val settings4Elastic = Settings.builder().put("cluster.name", "elasticsearch").build()
val uri4Elastic  = ElasticsearchClientUri(localhost, 9300)
val client4Elastic = ElasticClient.transport(settings4Elastic, uri4Elastic)

I am attempting to use the new Elasticsearch server.  I tried this, and it doesn't work:

// Create our client that will talk to Elasticsearch server to index Kafka data
val settings4Elastic = Settings.builder().put("cluster.name", "elasticsearch").build()
val uri4Elastic  = ElasticsearchClientUri("http://indexing-es.xxcorp.com", 80)
val client4Elastic = ElasticClient.transport(settings4Elastic, uri4Elastic)

This doesn’t work:

// Create our client that will talk to Elasticsearch server to index Kafka data
val settings4Elastic = Settings.builder().put("cluster.name", "elasticsearch").build()
val uri4Elastic  = ElasticsearchClientUri("indexing-es.xxcorp.com", 80)
val client4Elastic = ElasticClient.transport(settings4Elastic, uri4Elastic)

Any ideas?

Thank you!!

**Comment by sksamuel** [comment]
If it used to work, and then you changed your elasticsearch server, then its obviously something to do with that. In this case it looks like you're trying to use the TCP client to connect to a HTTP port. @RPGambit2

**Comment by RPGambit2** [comment]
Stephen,

Hi.  Thanks for all your previous help.   I'm not really sure what I should use now to create my client.   I am using elasticsearch 5.   I am able reach the new company setup endpoint in my browser so for example, in my browser, I can go to the url:

http://indexing-es.xxcorp.com/_cat/indices

and I get the following:

yellow open .kibana 5JjRpYuyTIWL3aMf9J8B2w 1 1 1 0 3.2kb 3.2kb

However, I'm not sure how to create the client or which type of client I need to create via elastic4s.

Do you have any good examples I can use to create my client for writing to elasticsearch in order to go out to the new elasticsearch server location on the company network?

The old way I was using (which went to my local hard drive) is no longer correct:
// Create our client that will talk to Elasticsearch server to index Kafka data
val settings4Elastic = Settings.builder().put("cluster.name", "elasticsearch").build()
val uri4Elastic = ElasticsearchClientUri(localhost, 9300)
val client4Elastic = ElasticClient.transport(settings4Elastic, uri4Elastic)

Thank you!
