### ISSUE TITLE
Support for elastic4s-http with elastic4s-circe

### ISSUE THREAD

**Issue by yurique** [sksamuel/elastic4s#792]
Hi!
I'm using `elastic4s-circe` for JSON and now trying to switch to the `HttpClient`.

With code like this:
```
import com.sksamuel.elastic4s.circe._
import com.sksamuel.elastic4s.http.HttpClient

//...
val elasticClient =
      HttpClient.fromRestClient(RestClient.builder(hosts: _*)).build())

elasticClient.execute(
  indexInto(indexName, docType).doc(json)
)    
```

I'm getting the following:
```
could not find implicit value for parameter format: com.sksamuel.elastic4s.JsonFormat[U]
[error]         elasticClient.execute(
[error]                              ^
```

The reason for this is that there's no Circe `Decoder` for `IndexResponse` and it can not be auto-derived like this:
```
import io.circe.generic.semiauto._
implicit val decodeIndexResponse: Decoder[IndexResponse] = deriveDecoder
```

because of `IndexResponse` has private fields, as far as I understand. And also because of it having "untyped" fields:
```
                         private val fields: Map[String, Any],
                         private val _source: Map[String, Any]
```

which Circe doesn't know how to handle.

So what I ended up doing for now is this:
```
import com.sksamuel.elastic4s.http.Shards
import com.sksamuel.elastic4s.http.index.IndexResponse
import io.circe._
import io.circe.generic.auto._
import cats.instances.either._
import cats.syntax.cartesian._

object ElasticSearchCodecs {

  private[this] def jsonObject2Java(m: JsonObject): Map[String, Any] =
    m.toMap.mapValues(json2Java)

  private[this] def json2Java(m: Json): Any =
    m.fold[Any](
      null,
      (jsonBoolean: Boolean) => jsonBoolean,
      (jsonNumber: JsonNumber) => jsonNumber.toBigDecimal,
      (jsonString: String) => jsonString,
      (jsonArray: Vector[Json]) => jsonArray.map(json2Java),
      (jsonObject: JsonObject) => jsonObject2Java(jsonObject)
    )

  private[this] implicit val decodeAnyMap: Decoder[Map[String, Any]] =
    Decoder.decodeJsonObject.map(jsonObject2Java)

  private implicit class JsonObjectExt(val o: JsonObject) extends AnyVal {
    def fieldAs[T: Decoder](name: String): Either[String, T] =
      o(name).toRight(s"$name missing").flatMap(_.as[T].left.map(_.message))
    def fieldAsDef[T: Decoder](name: String, d: T): Either[String, T] =
      o(name).map(_.as[T].left.map(_.message)).getOrElse(Right(d))
  }

  implicit lazy val decodeIndexResponse: Decoder[IndexResponse] =
    Decoder.decodeJsonObject.emap(
      o =>
        (
          o.fieldAs[String]("_id") |@|
            o.fieldAs[String]("_index") |@|
            o.fieldAs[String]("_type") |@|
            o.fieldAs[Long]("_version") |@|
            o.fieldAs[String]("result") |@|
            o.fieldAsDef[Boolean]("forced_refresh", false) |@|
            o.fieldAsDef[Boolean]("found", false) |@|
            o.fieldAsDef[Long]("totalHits", 0L) |@|
            o.fieldAsDef[Shards]("shards", Shards(0, 0, 0)) |@|
            o.fieldAs[Boolean]("created") |@|
            o.fieldAsDef[Map[String, Any]]("fields", Map.empty[String, Any]) |@|
            o.fieldAsDef[Map[String, Any]]("_source", Map.empty[String, Any])
        ).map(IndexResponse.apply))

}

```

Ant it seems to work. Not sure if there's a better way, and where to put it if it ends up in elastic4s (it depends both on `elastic4s-http` and `elastic4s-circe`, so can't really put into one of these.

The `decodeIndexResponse` would be unnecessary if `IndexResponse` didn't have private vals - is there a strong reason for that?

**Comment by sksamuel** [comment]
I'm happy to drop the private vals, that's just to hide the _un-java_ like variable names, like `doc_count`.  I can't do anything about the `Any` and `AnyRef`, as for instance the Aggregations in search response needs those.

**Comment by yurique** [comment]
I will try configuring `elastic4s-http`+`elastic4s-circe` to use with more than just `indexInto` a bit later, and will try to figure out the better way of doing all this without extra boilerplate :slightly_smiling_face:

**Comment by muuki88** [comment]
#786 duplicates this issue, I guess.

**Comment by muuki88** [comment]
I started to work on this, but I'm not sure how far I will come.
The main idea is to type `SearchResponse` correctly. Ideally it would look like this

```scala
case class SearchResponse[Source, Field, Aggregations](
   // meta stuff
   hits: SearchHits[Source, Filed],
   aggregations: Aggregations
)

case class SearchHit[Source, Fields](
  // ...  meta stuff
  fields: Fields,
  source: Source
) extends Hit

case class SearchHits[Source, Fields](
   // meta stuff
   hits: Array[SearchHit[Source, Fields]]
)
```

You could still get the old behaviour by defining `Source`, `Fields` and `Aggregation` types `Map[String, AnyRef]`. 

The problem is that the implicit resolution for the `HttpExecutable[T, U]` doesn't work if `U` has a generic type itself.

**Comment by sksamuel** [comment]
The issue is the way nested aggregations are returned in the json.

**Comment by muuki88** [comment]
What's the issue? I startet with the Hits and Fields :disappointed: 
I'll take a look at the aggregations.

**Comment by sksamuel** [comment]
It's the fact the aggregations are siblings of named fields. So you don't
know what they are in advance.

On 18 Mar 2017 19:30, "Nepomuk Seiler" <notifications@github.com> wrote:

What's the issue? I startet with the Hits and Fields 😞
I'll take a look at the aggregations.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/issues/792#issuecomment-287568995>,
or mute the thread

**Comment by muuki88** [comment]
I guess it would be possible with some shapeless/macro sorcery, but I'm by no means an expert in this field. Still, if we type source, fields and aggregations, things should stay as they are at the moment. If I understand this correctly the current usage is like this

```scala
val response: SearchResponse = ???
response.aggregations("my_aggregation").asInstanceOf[Map[String, AnyRef]]("value").toString.toDouble
```
Error handling like null checking, class cast exceptions and invalid paths have to  be checked manually every time. On the other hand, if you have a type

```scala
type Source = Unit
type Field = Unit

// aggregations representation
case class AggregationValue[T](value: T]
case class MyAggregation(
  my_aggregation: AggregationValue[Double]
)
// and the response looks like this
val response: SearchResponse[Source, Field, MyAggregation] = ???

response.aggregations.my_aggregation.value
```

We get a sane model back and have to handle json-parsing errors instead.

**Comment by sksamuel** [comment]
Ok so the json response is like:

source,
fields,
hits,
agg1,
agg2,
agg3

And so on. How do you strongly type the named variables but not the zero or
more aggregations. What do your case classes look like.

And shapeless might work well for circe but it has to work for jackson etc
as well as the raw HitReader.

**Comment by muuki88** [comment]
Yes, using shapeless for creating typesafe `SearchDefinition` <-> Result case classes would be hard to get right for all json libs. I guess this is at this point way beyond my knowledge.

However the classes for `SearchResponse` should be pretty straightforward. The code as above ( but with optional handling)

```scala
case class SearchResponse[Source, Field, Aggregations](
   // meta stuff
   hits: SearchHits[Source, Filed],
   aggregations: Option[Aggregations]
)

case class SearchHit[Source, Fields](
  // ...  meta stuff
  fields: Fields,
  source: Source
) extends Hit

case class SearchHits[Source, Fields](
   // meta stuff
   hits: Array[SearchHit[Source, Fields]]
)
```

I modeled this after the pre-existing case classes and the sample json query I made

```json
{
  "took": 16,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1,
    "hits": [
        ...
    ]
  },
  "aggregations": {
    "avg_age": {
      "value": 37.5
    }
  }
}
```

**Comment by sksamuel** [comment]
SearchResponse is already ok. I'm on my phone so hard to paste but check
out the sub aggregations responses and see how its siblings of the fixed
field names.

**Comment by muuki88** [comment]
No problem :smile: 

Here is a compiling example

```scala
import com.sksamuel.elastic4s.JsonFormat
import io.circe.generic.auto._

import scala.concurrent.Future

case class SearchDefinition(query: String)

case class SearchResponse[Source, Field, Aggregations](
    // meta stuff
    hits: SearchHits[Source, Field],
    aggregations: Option[Aggregations]
)

case class SearchHit[Source, Fields](
    // ...  meta stuff
    fields: Fields,
    source: Source
)

case class SearchHits[Source, Fields](
    // meta stuff
    hits: Array[SearchHit[Source, Fields]]
)

trait HttpExecutable[Req, Rep] {
  def execute(request: Req): Future[Rep]
}

object HttpExecutable {

  implicit def searchExecutable[Source, Field, Aggregations](
      implicit format: JsonFormat[SearchResponse[Source, Field, Aggregations]])
    : HttpExecutable[SearchDefinition, SearchResponse[Source, Field, Aggregations]] =
    new HttpExecutable[SearchDefinition, SearchResponse[Source, Field, Aggregations]] {
      override def execute(request: SearchDefinition): Future[SearchResponse[Source, Field, Aggregations]] = {
        // execute query and map response to SearchResponse[Source]
        ???
      }
    }

}

object Test {

  case class Person(name: String, age: Int)
  case class AggregationValue[T](value: T)
  case class AverageAge(averageAge: AggregationValue[Double])

  implicitly[HttpExecutable[SearchDefinition, SearchResponse[Person, Unit, AverageAge]]]

}
```

**Comment by sksamuel** [comment]
Where's the aggregations type?

**Comment by muuki88** [comment]
It's the last generic type parameter on the `SearchResponse`. The user needs to provide this parameter.

**Comment by sksamuel** [comment]
Ok I'm confused. I don't think I'm explaining the issue lol but you'll have
to wait until I'm back in London on my real computer:)

**Comment by muuki88** [comment]
Yeah. I think we are confusing each other pretty good 😂 no rush. Good trip home.Am 18.03.2017 9:27 nachm. schrieb Stephen Samuel <notifications@github.com>:Ok I'm confused. I don't think I'm explaining the issue lol but you'll have
to wait until I'm back in London on my real computer:)

**Comment by sksamuel** [comment]
So here we go.

SearchResponse returns fields, such as `timed_out`, `_scroll_id` and so on. So we model this in a case class.

```
case class SearchResponse(timed_out: Boolean, _scroll_id: String)
```

Another one is aggregations, so we can do:

```
case class Aggregations(doc_count_error_upper_bound:Int, sum_other_doc_count:Int)
case class SearchResponse(timed_out: Boolean, _scroll_id: String, aggregations: Aggregations)
```

So far so easy.
Now the aggregations model also needs to include subaggregations, but they aren't returned as an array with an name like subaggs or anything, they are just siblings of fields like `doc_count_error_upper_bound` and `buckets`. So you have json like,

```json
aggregations: {
  myagg: {
     buckets: [],
     doc_count_error_upper_bound: 3,
     subagg1: {
       buckets: [],
       ...
     },
     myothersubagg: {
       buckets: [],
     ...
     }
  }
}
```

How do you model that as a case class. Something like 

```
case class Aggregation(buckets:Seq[Bucket], doc_count_error_upper_bound:Int, sum_other_doc_count:Int, subaggs:Map[String, Aggregation]
```

But - here is the issue - how do you get your json library to unmarshall the named fields as proper fields, and any other field as an aggregation type.

**Comment by muuki88** [comment]
My approach would have delegated this issue completely to the caller with a generic parameter on the `SearchResponse` class. Elastic4s could provide a base trait that describes the basic structure.

```scala
trait Aggregation {
  val doc_count_error_upper_bound: Int
  val sum_other_doc_count: Int
}
case class SearchResponse[A <: Aggregation](timed_out: Boolean, _scroll_id: String, aggregations: Aggregations)
```

I know that this puts more responsibility on the user than would be preferable, but it's still better than using `Map[String, AnyRef]` and only support json libraries that use reflection.

**Comment by sksamuel** [comment]
So the user would have to create a type for every different query they make? I suppose that could work although its a hassle for the user. My approach is less "type safe" but all this is hidden from the user. So what's the advantage of using a type parameter approach?

**Comment by muuki88** [comment]
> So the user would have to create a type for every different query they make?

Yes. Users can abstract as they wish over the generic parameter.

> My approach is less "type safe" but all this is hidden from the user. So what's the advantage of using a type parameter approach?

## Current status

The `SearchResponse` is a final case class with no generic parameters. There are three fields  that are untyped. There are three variables typed to `Map[String, AnyRef]`

* `aggregations` ( directly on `SearchResponse` )
* `fields` and `_source` in the `SearchHit` model

This leads to the following properties

* hard or unable to use libraries that make use of strong typings and no reflection
* hard to use when you don't know the results of the query
* more complicated error handling due to a lot of null-checking and class casting

*Example*

We make a search query where we what to access the source and some aggregations.

```scala
val searchResponse: searchResponse = ??? // executed query here
val hits = searchResponse.hits
val firstHit = hits.head
```

At this point as a user I have no idea what the result looks like. If I want to access the source I have to

* `firstHit.sourceAsMap.get("a_field").map(_.asInstanceOf[Int]).getOrElse(0)` - hope that we use the right Int type that our json lib uses
* `Json.parse(firstHit.sourceAsString)` and then parse the json to a model or traverse the json

## Proposal

The `SearchResponse` has three generic type parameters that can be used to defined the format for

* the `aggregation` field
* the `_source` field
* the `fields` field

This leads to the following properties

* Error handling for an invalid structured  formatted result is in a single place: the json deserializing
* If I get a valid result, I can be sure as a user that I can access all values
* I get documentation for my queries for free, because I have to write model classes that map to the result of a single query

*Example*

In this case we need to define some model classes. Let's say we query _persons_

```scala
// we don't ask for fields, so we type it to Unit
type Fields = Unit

// a very basic Person representation
case class Person(name: String, age: Int)


// aggregations value helper
case class AggregationValue[T](value: T)

// our aggregation for a person query.
case class PersonAggregations(
  avgAge: AggregationValue[Double]
)
```

When we execute our predefined query, the result will look like this

```scala
val searchResponse[Person, Fields, PersonAggregations]: searchResponse = ??? // executed query here
val hits: Array[SearchHits[Person, Fields] = searchResponse.hits
val firstHit: SearchHit[Person, Fields] = hits.head
```

To execute this query we need `JsonFormat` definitions for all three type parameters. 

### What about legacy code?

You can use `Map[String, AnyRef` as a parameter for all three generic parameters to get the old behaviour, e.g.

```scala
// we don't ask for fields, so we type it to Unit
type Result = Map[String, AnyRef]

val response: SearchResponse[Result, Result, Result] = ???
```

**Comment by yurique** [comment]
If I may, here is my two cents :) - my take on this would be not to put any extra burden on the DSL user.

As a user I don't really care about the under-the-hood representations `elastic4s` uses, and having it as a `Map[String, AnyRef]` inside `elastic4s` inner-workings seems completely fine - all I want as a user is to read the responses using the provided DSL, as it is right now.

So my issue initially was that there were no readily available `Circe` type-class instances for decoding the responses from JSON to `elastic4s` internal representation. But it's doable - like for example ` implicit val decodeAnyMap: Decoder[Map[String, Any]]`  and `implicit val decodeIndexResponse: Decoder[IndexResponse] ` in the description. If we have all needed decoders available in some  module (like `elastic4s-http-circe`) it would do the trick for me.

Another thing I noticed is in the `SearchHit` class. It has `_source` as a `Map[String, AnyRef]` and then 

```scala
  override def sourceAsString: String = SourceAsContentBuilder(_source).string()
```

and in `com.sksamuel.elastic4s.circe` we have this:

```scala
  implicit def hitReaderWithCirce[T](implicit decoder: Decoder[T]): HitReader[T] = new HitReader[T] {
    override def read(hit: Hit): Either[Throwable, T] = decode[T](hit.sourceAsString)
  }
```


So the `SourceAsContentBuilder(_source).string()` is called to convert from `Map[String, AnyRef]` to a `String` every time one decodes a hit to a case class. And on the other hand `_source` as a `Map[String, AnyRef]` is likely rarely used. So maybe as an optimization we should keep the string and build the `Map[String, AnyRef]` when it's needed?

**Comment by sksamuel** [comment]
The reason `source` is a Map is that some json libraries (Jackson for example) don't really handle Strings for "subsets" of the json tree. Jackson is my primary use case - I know it's not the most _scalay_ json library, but its probably the most popular (Spark uses it and that's probably the biggest Scala library at the moment, so that's good enough for me).

It's really a difficult situation as a library writer. I'm on record as saying I hate the fact Scala has so many Json libraries. I think its a joke. Who fucking cares what library is used for Json really. And yet people keep inventing new ones. And when it's suggested the Scala stdib has a json AST, all hell breaks loose. Sometimes I think the Scala community is its own worst enemy when it comes to things like this.

Anyway, I'm not sure where I sit on regards to making `SearchResponse` use type parameters. On one hand, what @muuki88 proposes is quite neat and gives us some nice type safety. On the other hand, Elasticsearch has this ethos, whether you like it or not, of embracing dynamic typing (at least loose typing of some sort in the sense that fields can be added adhoc, and lots of conversions go on) and so being able to just see the source/fields easily is how it was designed.

At the moment, you can get your strong typing by calling `to[T]` or `safeTo[T]` to get proper types. Or if you just want to grab a field out then `source` works fine. Maybe its a case of it just works as it is, so why change it? If we add `Map[String, AnyRef]` typeclasses to circe we can fix circe to work with it.

**Comment by yurique** [comment]
Another thing I'm thinking is that for decoding into internal structures under the hood there's no real need to use Circe, or whatever else - we might as well just have a default JSON library (Jackson) as a dependency of the `elastic4s-http` module; and when one wants to use another JSON lib for documents encoding/decoding - then we have a module that provides `hitReaderWithCirce` and `indexableWithCirce` for it (no need for `jsonFormatWithCirce` in this case).

I like @muuki88's suggestion as well, and I think it would be nice to have as an alternative option, but it seems to me in many cases it would be a bit too cumbersome to use/support (like in one of the cases in our project we have a list of 30+ names for aggregations that are potentially used in a single query - many levels nested and added-or-not dynamically depending on the conditions - that would be quite a monstrous data structure with case classes and `Option`s everywhere :laughing: )

**Comment by sksamuel** [comment]
I'm against having `elastic-http` bring in a default json library for two reasons. One, I've had people complain about it before, and two, it can clash with the versions brought in by other libraries (again spark is a big factor here).

**Comment by yurique** [comment]
Yeah, I see.

Well, I'm going to try something like this when I get to play more with HTTP client: add both  `elastic4s-jackson` and `elastic4s-circe` to deps and then

```scala
import com.sksamuel.elastic4s.jackson.ElasticJackson.Implicits.format
import com.sksamuel.elastic4s.circe.hitReaderWithCirce
import com.sksamuel.elastic4s.circe.indexableWithCirce
```

**Comment by muuki88** [comment]
> It's really a difficult situation as a library writer. I'm on record as saying I hate the fact Scala has so many Json libraries

I'm on this one with you @sksamuel . This is why I tried to keep this change more from a code perspective than a library perspective. 

> Elasticsearch has this ethos, whether you like it or not, of embracing dynamic typing (at least loose typing of some sort in the sense that fields can be added adhoc, and lots of conversions go on) and so being able to just see the source/fields easily is how it was designed.

I think this is the biggest one. Elasticsearch's API is quite often... let's say grown. By introducing generics we hide the fact that elasticsearch may do a lot of weird stuff under the hood. 

Still I think this is a necessary change for a better experience in the long run. Because using untyped maps in scala ( and java ) is so hard, error prone and cumbersome (e.g. "what's the field spelled?"). 

> I like @muuki88's suggestion as well, and I think it would be nice to have as an alternative option, but it seems to me in many cases it would be a bit too cumbersome to use/support (like in one of the cases in our project we have a list of 30+ names for aggregations that are potentially used in a single query - many levels nested and added-or-not dynamically depending on the conditions - that would be quite a monstrous data structure with case classes and Options everywhere :laughing: )

I think it shouldn't be an alternative. Otherwise it's really confusing. I would only try to make this change if I'm sure that existing code only has to be changed manually like this:

```scala
// old code
val searchResponse: SearchResponse = ???
// new code
val searchResponse: SearchResponse[Map[String, AnyRef], Map[String, AnyRef], Map[String, AnyRef]]
```

This way you can keep all the `source("x").as[Map[String, AnyRef]]("y").as[Double]` stuff in your code and can replace this with more meaningful types. There are plenty of ways to structure your ADTs in scala with plain case classes, lenses, code generation, marcros and who knows what. The main point here is: you are able to choose.

I think the http client shouldn't be to opinionated about the way a user has to structure and build his/her code base. Even I understand the point that this puts more visible burden on the user. On the other hand: Having to deal with null and untyped maps is the reason people use scala and not java.

@sksamuel if there's a chance you would accept a pull request with this change, I'm going to start working on this.

**Comment by sksamuel** [comment]
What about if `SearchResponse` can stay untyped, and you add methods that do the typing.  Similar to how we have `to[T]` at the moment, why not add a `agg[T]` method?

**Comment by muuki88** [comment]
This wouldn't solve the issue with using `circe` and co as there as still these untyped maps.

Thinking more about what @yurique said, reusing the `HitReader` idea. We may also change the structure so that you have generic `ResponseReader`. This could look something like

```scala
// no jsonFormat anymore
trait HttpExecutable[T, U] {
  def execute(client: RestClient, request: T): Future[U] 
}

// S = success, E = Error
trait ResponseReader[S, E] {
  // string, hiding the apache http reponse underneath
  def parseJsonResponse(string: Content): Either[E, S]
}

// e.g. in the SearchImplicits


implicit def searchHttpExecutable[S,E]()(implicit reader: ResponseReader[S,E]): HttpExecutable[SearchDefinition, Either[S,E]] = new HttpExecutable[SearchDefinition, Either[S,E]] {
   def execute(client: RestClient, request: SearchDefinition): Future[Either[E,S]] = {
       executeAsyncAndMapResonse()
   }
}

```

We could define generic `ResponseReader` definitions when there's a `JsonFormat` available. Like

```scala
implicit def responseReaderFromJsonFormat[U]()(implicit jsonFormat: JsonFormat[U]): Either[Throwable, U] = new ResponseReader[Throwable, U] {
   def parseJsonResponse(content: String): Either[Throwable, U] = Try(
       jsonFormat.fromJson(content)
   ).toEither
}
```

This just came up after a big sip of coffee. So it maybe not that of a good idea :P

**Comment by sksamuel** [comment]
Can we add AnyRef typeclasses to circe or is that not possible?

Lets define our goal. Is it to have a nice implementation that never uses AnyRef or is it just to hide that from the user? If it's the latter then it doesn't matter too much how horrific it looks internally to make it work.

At the moment SearchResponse doesn't carry type info. And if you want types out of it you use `to` with a HitReader typeclass. This also means you can grab a single field if that's your desire.

The way it works in elastic might not be very scala like so you can make two choices. Try to hide it and make the api idiomatic scala - fully typed where possible and so on. Or work with elastic and do what you can to augment it with scala friendly stuff. I initially tried the former and it was a nightmare as elastic change things quite often and people expect it to work like the elastic documentation says. That's why we have the HitReader typeclass. It doesn't try to hide what elastic returns but means you can do things 'properly' if you want.

Anything we can do to make it easier to work in scala way is good but I do think we shouldn't try to hide the fact elastic has a bit of a horrible api in places. Otherwise the barrier for entry is higher than it needs to be.

Indexing is another example. Pass in a giant json string, scala map, or use the Indexable typeclass. Whatever you like to do we can accomodate it and it seems to work. In practice I imagine most people with decent Scala experience are using the typeclass but when you first come to elastic4s you can still do it the Java way if you want.

So perhaps we can find a way to get the best of all worlds.

**Comment by solicode** [comment]
`HitReader` and `Indexable` seem reasonable to me, because the content of `source` is completely arbitrary, so it makes sense that the user is going to have to provide typeclasses for that. What is complicating all this is parsing `SearchResponse`, `GetResponse`, etc. Right now, unless using a reflection-based library like Jackson, the user has to provide typeclasses for all the response types as well. That's not obvious in my opinion. I don't see how even automatic derivation is going to fix that. This is what #841 is all about, right? Doesn't this mean that elastic4s has to provide all the Decoders for each response type? And multiplied for each Json library you want to support (except Jackson)? I'm not seeing a way around that. Besides, I think explicit code is going to be needed regardless, because I'm assuming you want types like `fields: Map[K, V]` not `fields: Option[Map[K, V]]` when `fields` or `source` is not present in the response.

I'm more familiar with play-json than Circe, but creating a minimal working example with `elastic4s-play-json` in its current state doesn't seem like it would work either. Unless you use play-json exclusively for `HitReader` and `Indexable`, and Jackson for the parsing of Elasticsearch responses with all the AnyRefs. But it sounds like you're trying to avoid using more than 1 JSON library at a time.

Anyway, the typeclass for AnyRef seems like it would work, even if it feels somewhat inelegant. But I think it should work okay with the `agg[T]` idea. Creating a bunch of typeclasses for all the responses still seems necessary though to me. Unless I'm missing something... which is definitely possible.

As for having everything be properly typed... that would be really nice, but it does seem like quite a challenge.

**Comment by sksamuel** [comment]
Thanks for the comments @solicode. I think the issue is `SearchResponse` has these AnyRef fields, which circe doesn't like. The other response types, say `UpdateResponse`, don't do that, so the automatic derivation can work for all the json modules. At least that's my understanding.

**Comment by solicode** [comment]
Interesting. Circe's auto derivation does more than I initially thought. So with some minimal work to help it out (and possibly handling those Options I mentioned earlier if it becomes a problem), it might not be too hard to get it to work with all the responses. Also, I didn't realize it could integrate with other libraries like that.

This is assuming the AnyRef approach is taken that is. Maybe there will be other ideas.

**Comment by muuki88** [comment]
> I think the issue is SearchResponse has these AnyRef fields, which circe doesn't like. The other response types, say UpdateResponse, don't do that, so the automatic derivation can work for all the json modules. At least that's my understanding.

Yes. This is what I have seen so far as well. `SearchResponse` is the only relevant thing ATM here. A `agg[T]` method wouldn't help, as you would have to provide a circe encoder for `Map[String, AnyRef]` first. Writing such an encoder brings more harm than help IMHO

- it's error prone and inefficient
- you parse and reparse 

> Circe's auto derivation does more than I initially thought

Unlike play-json where you can semi-automatic dervice you codes with `Json.format[YouCaseClass]`, circe provides a full, automatic derivation, which saves a lot of manual work. It handles all kind of default containers like `Option`, `Seq` and `Map`.

## Goals

> Lets define our goal. Is it to have a nice implementation that never uses AnyRef or is it just to hide that from the user?

Good point. For me there are two goals

1. Type the search response
2. Make it possible to use non-reflection-based json libraries like circe

With _1_ one solves basically _2_. 

> Anything we can do to make it easier to work in scala way is good but I do think we shouldn't try to hide the fact elastic has a bit of a horrible api in places. Otherwise the barrier for entry is higher than it needs to be.

I agree on that. By providing generics we bubble this api up to the user.

I'll see if I can implement two prove-of-concepts for a `HitReader` based approach and for a generic approach. Discussing this on a real example may be easier.

**Comment by sksamuel** [comment]
I want to keep SearchResponse untyped because its how its been done previously, so fewest changes, and because I don't really want to do `SearchResponse[Map[String, AnyRef], Map[String, AnyRef], Map[String, AnyRef]]` everywhere.

So I've had an idea. I'll have a go at implementing something as well see what you think.

**Comment by cchantep** [comment]
Seems the issue is still there, my2cts workaround for `indexInto` :

```scala
import io.circe.Decoder
com.sksamuel.elastic4s.http.index.IndexResponse

implicit val indexRespDecoder: Decoder[IndexResponse] =
  Decoder.forProduct8("id", "index", "type", "version", "result", "forced_refresh", "shards", "created")(IndexResponse.apply)
```

**Comment by sksamuel** [comment]
I'm starting to like your ResponseParser idea @muuki88

**Comment by sksamuel** [comment]
Take a look at branch https://github.com/sksamuel/elastic4s/tree/spike/responsehandler.

I've added `ResponseHandler` and updated the way the `HttpExecutable`s work. This means we can do nicer custom handling, such as required for #832. 

There's a default response handler which still uses a `JsonFormat, so that's fine for when we have solid types we can use like `UpdateResponse`, which would work for all json libraries. 

The challenge now is to get a response handler that works for Circe. The problematic cases are any return types which use AnyRefs, so that's `SearchResponse`, `GetResponse` mostly. 

One option is your preferred type parameter, meaning the user has to provide a type every time. What about introducing a new type called JsonObject, like the typical Json ASTs do to present the json primitive, and implementing the six or seven Circe decoders needed. Then we can do `source: Map[String, JsonType]` or something, and it gives us a potential half way house between no typing, and forcing the user to specify a type every time. 

I'd be a lot happier about the type parameter if there was a way to default to what we have now very easily, with no extra burder on the user.

**Comment by sksamuel** [comment]
@muuki88 any further thoughts? Maybe we should just package jackson into the http module and use it internally, leaving people free to use circe with the public api?

**Comment by muuki88** [comment]
@sksamuel I haven't had the time to look at the changes on your branch :(

> Maybe we should just package jackson into the http module and use it internally, leaving people free to use circe with the public api?

Not sure if parsing multiple times is the way forward. Not sure if adding abstraction or dependency complexity is the lesser evil.

> I'd be a lot happier about the type parameter if there was a way to default to what we have now very easily, with no extra burder on the user. Another issue is that elasticsearch uses Object in so many places, I wonder if the user is going to have to end up specifying ridiculous amounts of types.

Personally, I favor more types, even if this sometimes means writing longer method calls, definitions, etc. The type system is one of the reasons I like scala so much. Also I like types as a compiled documentation that you cannot forget, because your code won't compile. 

I fully understand that for some developers adding a lot of type information feels like a burden. For others it means safety and documentation. In the end this is your decision in which direction you want elastic4s to progress. Either way I'll try my best to support you :)

**Comment by sksamuel** [comment]
I like types too, but it doesn't matter to the end user how elastic4s is written, as long as it works. I personally feel, given that elasticsearch is quite _dynamic_ and returns json, that allowing the user to get a handle on the raw json and marshall to types after that, is the way to do the API. So that side, what's the best solution?

I've been playing around for a few days, and I can't see a way to keep circe/jackson/everyone else happy. Spark uses Jackson internally, and no one complains about that - they're free to use Circe themselves. So a similar solution for elastic4s might be good - and it means a more obvious API as you won't need to import JsonFormat everywhere.

wdyt?

**Comment by muuki88** [comment]
> I personally feel, given that elasticsearch is quite dynamic and returns json, that allowing the user to get a handle on the raw json and marshall to types after that, is the way to do the API.

Yeah. This is probably a good way to start and learn what users build around this.

**Comment by sksamuel** [comment]
Circe now works with 5.4.
